---
- name: Runc | Check if runc binary exists
  ansible.builtin.stat:
    path: /usr/local/sbin/runc
  register: runc_binary_status

- name: Runc | Download runc
  ansible.builtin.get_url:
    url: https://github.com/opencontainers/runc/releases/download/v1.3.1/runc.amd64
    dest: /tmp/runc.amd64
    mode: '0644'
  when: not runc_binary_status.stat.exists

- name: Runc | Copy runc binary into target folder
  ansible.builtin.copy:
    src: "/tmp/runc.amd64"
    dest: "/usr/local/sbin/runc"
    mode: "0755"
    remote_src: true
  become: true
  when: not runc_binary_status.stat.exists

- name: Runc | Clean up downloaded file
  ansible.builtin.file:
    path: /tmp/runc.amd64
    state: absent
  when: not runc_binary_status.stat.exists
