name: Run Ansible Tests

on:
  push:
    branches:
      - '**' 
    paths:
      - 'configure/**'
      - '.github/workflows/run_ansible_tests.yml' 
jobs:
  molecule:
    name: Molecule (Vagrant)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Set up Vagrant and VirtualBox
        uses: hashicorp/setup-vagrant@v2

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible molecule 'molecule-plugins[vagrant]'

      - name: Run Molecule tests
        run: |
          cd configure
          molecule test --all
